In [1]:
import numpy as np


In [2]:
print("Hello world")

Hello world


In [3]:
myarr = np.array([[3,4,345,33]],np.int64)

In [4]:
myarr


array([[  3,   4, 345,  33]], dtype=int64)

In [5]:
myarr[0,3]

33

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
myarr[0,1]=56

In [10]:
myarr

array([[  3,  56, 345,  33]], dtype=int64)

Array Creation :Conversion from other Python Structure

In [20]:
listarray  = np.array([[2,4,4,],[556,5,4],[3,3,3]])

In [21]:
listarray

array([[  2,   4,   4],
       [556,   5,   4],
       [  3,   3,   3]])

In [22]:
listarray.dtype

dtype('int32')

In [23]:
listarray.shape

(3, 3)

In [24]:
listarray.size

9

In [25]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [26]:
zeros = np.zeros((2,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
rng = np.arange(19)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [34]:
lspace= np.linspace(1,10,4)

In [33]:
lspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [35]:
emp = np.empty((4,6))

In [36]:
emp

array([[1.06460513e-311, 7.50979782e-322, 0.00000000e+000,
        0.00000000e+000, 1.24610383e-306, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 7.06269593e-077,
        2.99067252e-067, 1.28448408e-057, 5.51681714e-048],
       [2.36945494e-038, 1.47900214e-076, 6.35226565e-067,
        2.72827734e-057, 1.17178620e-047, 6.01347002e-154],
       [5.03278346e-038, 3.77780862e+180, 1.15998412e-028,
        6.48224638e+170, 3.67145870e+228, 1.60920290e+295]])

In [39]:
 emp_like = np.empty_like(zeros)

In [40]:
emp_like

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
ide = np.identity(10)

In [44]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
ide.shape

(10, 10)

In [60]:
arr = np.arange(99)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [65]:
arr.shape

(99,)

# Axis

In [70]:
x= [[1,2,4],[4,4,56],[33,44,34]]

In [72]:
ar=np.array(x)

In [73]:
ar

array([[ 1,  2,  4],
       [ 4,  4, 56],
       [33, 44, 34]])

In [74]:
ar.sum(axis=0)

array([38, 50, 94])

*** verticically summ ***

In [77]:
ar.sum(axis=1)

array([  7,  64, 111])

*** Hroizontally summ ***

In [78]:
ar.T

array([[ 1,  4, 33],
       [ 2,  4, 44],
       [ 4, 56, 34]])

In [79]:
ar.flat

In [80]:

for item in ar.flat:
    print(item)

1
2
4
4
4
56
33
44
34


In [81]:
ar.ndim

2

*** Nop of dimension ***

In [83]:
ar.nbytes

36

In [98]:
one = np.array([10012,1,2,34,2,267])

In [99]:
one.argmax()

0

argmax show where the max emements are

In [100]:
one.argsort()

array([1, 2, 4, 3, 5, 0], dtype=int64)

shows the position of sorting 

In [101]:
ar.argmin()

0

In [103]:
ar

array([[ 1,  2,  4],
       [ 4,  4, 56],
       [33, 44, 34]])

In [102]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)